(() => { "use strict";
  const socket=io(), $=(id)=>document.getElementById(id);
  const el={lobby:$("lobbyScreen"),game:$("gameScreen"),create:$("createRoomButton"),join:$("joinRoomButton"),inputCode:$("roomCodeInput"),roomMessage:$("roomMessage"),code:$("roomCodeDisplay"),role:$("playerRole"),newGame:$("newGameButton"),rules:$("rulesButton"),rulesDialog:$("rulesDialog"),closeRules:$("closeRulesButton"),zombie:$("zombieDescription"),zombieImage:$("zombieImage"),generate:$("generateItemButton"),item:$("itemDescription"),status:$("auctionStatus"),result:$("resultPanel"),resultTitle:$("resultTitle"),resultText:$("resultText")};
  let state=null,myPlayer=null,roomCode=null; const sessionKey="zombie-auction-session";
  const zombieImages={"Corredores de Extermínio":"assets/zombies/exterminio.png","Infectados de The Last of Us":"assets/zombies/the-last-of-us.png","Enxames de Guerra Mundial Z":"assets/zombies/guerra-mundial-z.png","Zumbis clássicos":"assets/zombies/zumbis-classicos.png","Infectados de REC":"assets/zombies/rec.png","Zumbis de Resident Evil":"assets/zombies/resident-evil.png","Caminhantes de The Walking Dead":"assets/zombies/walking-dead.png","Infectados de Left 4 Dead":"assets/zombies/left-4-dead.png","Infectados de Invasão Zumbi":"assets/zombies/invasao-zumbi.png","Zumbis de Zumbilândia":"assets/zombies/zumbilandia.png"};
  const bidInput=(p)=>$("player"+(p+1)+"Bid"),bidButton=(p)=>$("player"+(p+1)+"BidButton"),withdrawButton=(p)=>$("player"+(p+1)+"WithdrawButton"),balance=(p)=>$("player"+(p+1)+"Balance"),inventory=(p)=>$("player"+(p+1)+"Inventory");
  const getSession=()=>{try{return JSON.parse(localStorage.getItem(sessionKey));}catch{return null;}}; const saveSession=(code,token)=>localStorage.setItem(sessionKey,JSON.stringify({code,token}));
  function leaveRoom(){state=null;myPlayer=null;roomCode=null;localStorage.removeItem(sessionKey);el.game.classList.add("is-hidden");el.lobby.classList.remove("is-hidden");el.inputCode.value="";el.roomMessage.textContent="";}
  function showGame(payload){state=payload.state;myPlayer=payload.player;roomCode=state.roomCode;el.code.textContent=roomCode;el.role.textContent="Você é o Jogador "+(myPlayer+1);el.zombie.textContent=state.zombie.description;el.zombieImage.src=zombieImages[state.zombie.name];el.zombieImage.alt="Cenário: "+state.zombie.name;el.lobby.classList.add("is-hidden");el.game.classList.remove("is-hidden");render();}
  const tagEmoji={mobility:"🚗",combat:"🛡️",medical:"🩹",food:"🥫",communication:"📻",shelter:"🏠"};
  function list(values){return values.length?values.map((entry)=>{const li=document.createElement("li");li.textContent=entry.tags.map((tag)=>tagEmoji[tag]).join("")+" "+entry.name+" — R$ "+entry.price;return li;}):[Object.assign(document.createElement("li"),{textContent:"Nenhum item ainda."})];}
  function render(){if(!state)return;state.players.forEach((player,p)=>{balance(p).textContent="R$ "+player.balance;inventory(p).replaceChildren(...list(player.inventory));updateControls(p);});el.item.textContent=state.item?state.item.tags.map((tag)=>tagEmoji[tag]).join("")+" "+state.item.name+" — "+state.item.description:"Gere um item para iniciar o leilão.";el.status.textContent=state.message;el.generate.disabled=!state.canGenerate||myPlayer!==0||Boolean(state.winner);el.result.classList.toggle("is-hidden",!state.winner);if(state.winner){el.resultTitle.textContent=state.winner.title;el.resultText.textContent=state.winner.explanation;}}
  function updateControls(p){const isMe=p===myPlayer,hasItem=Boolean(state.item),player=state.players[p],hasMoney=player.balance>=1,bid=Number(bidInput(p).value),minBid=Math.max(1,state.currentBid+1),mayStart=state.bidder!==null||p===state.starter,canBid=isMe&&hasMoney&&hasItem&&mayStart&&!player.withdrawn&&!state.players[1-p].withdrawn&&state.bidder!==p&&Number.isInteger(bid)&&bid>=minBid&&bid<=player.balance,canClaim=isMe&&hasMoney&&hasItem&&state.players[1-p].withdrawn&&state.bidder===p;bidInput(p).disabled=!isMe||!hasMoney||!hasItem||player.withdrawn||!mayStart||Boolean(state.winner);bidButton(p).textContent=canClaim?"Pegar item":"Dar lance";bidButton(p).disabled=!(canBid||canClaim);withdrawButton(p).disabled=!(isMe&&hasItem&&!player.withdrawn&&!state.players[1-p].withdrawn&&state.bidder!==p&&!state.winner);}
  const emit=(action,data={})=>socket.emit(action,{roomCode,...data});
  el.create.addEventListener("click",()=>socket.emit("create-room"));el.join.addEventListener("click",()=>{const code=el.inputCode.value.trim().toUpperCase();if(!/^[A-Z0-9]{6}$/.test(code))return el.roomMessage.textContent="Informe um código de sala com 6 caracteres.";const saved=getSession();socket.emit("join-room",{roomCode:code,token:saved?.code===code?saved.token:null});});el.inputCode.addEventListener("input",()=>{el.inputCode.value=el.inputCode.value.toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,6);});el.newGame.addEventListener("click",leaveRoom);el.rules.addEventListener("click",()=>el.rulesDialog.showModal());el.closeRules.addEventListener("click",()=>el.rulesDialog.close());el.generate.addEventListener("click",()=>emit("generate-item"));
  [0,1].forEach((p)=>{bidInput(p).addEventListener("input",()=>{bidInput(p).value=Math.max(1,Math.trunc(Number(bidInput(p).value)||1));render();});bidButton(p).addEventListener("click",()=>{if(p!==myPlayer)return;const other=state.players[1-p];if(other.withdrawn&&state.bidder===p)emit("claim-item");else emit("place-bid",{amount:Number(bidInput(p).value)});});withdrawButton(p).addEventListener("click",()=>p===myPlayer&&emit("withdraw"));});
  socket.on("room-joined",({roomCode:code,token,player,state:next})=>{saveSession(code,token);showGame({player,state:next});});socket.on("state",(next)=>{state=next;render();});socket.on("room-error",(message)=>el.roomMessage.textContent=message);socket.on("connect_error",()=>el.roomMessage.textContent="Não foi possível conectar ao servidor. Abra o jogo pelo endereço publicado, e não pelo arquivo index.html.");socket.on("action-error",(message)=>{if(state){state.message=message;render();}});
})();
